### ISSUE TITLE
Using a composite value as label

### ISSUE THREAD

**Issue by frcroth** [OmenApps/django-tomselect#7]
I am wondering if the following is possible. We have a User model where the username is an id, so humans can identify User objects by first name and last name.
Is it possible to use the concatenation of first name and last name, i.e. full name as the label_field and display that in the selection list? (Ideally without adding/modifying the User model)

**Comment by jacklinke** [comment]
Sorry it took a year to get back to you on this 😖

Finally had time to do a full update of this package, along with examples. The way to approach this would be to use the tabular option, which would allow you to have the first name in a column and the last in another. Either or both could be searchable.

This is what it would look like in your project.

autocomplete view:

```python
class UserAutocompleteView(AutocompleteModelView):
    """Autocomplete that returns all User objects."""

    model = User
    search_lookups = ["first_name__icontains", "last_name__icontains"]
    page_size = 20
    value_fields = ["id", "first_name", "last_name"]
```

forms.py

```python
class UserSelectionForm(forms.Form):
    tomselect_tabular = TomSelectModelChoiceField(
        config=TomSelectConfig(
            url="autocomplete-user",
            value_field="id",
            label_field="first_name",
            highlight=True,
            open_on_focus=True,
            preload="focus",
            plugin_dropdown_header=PluginDropdownHeader(
                show_value_field=False,
                label_field_label="First",
                extra_columns={"last_name": "Last"},
            )
        )
    )
```

I know you probably moved on a long time ago since I failed to reply, but if you ever want to evaluate this package for your projects again, we now have [detailed docs](https://django-tomselect.readthedocs.io/en/latest/usage.html) and 15 different usage examples in the [example project](https://github.com/OmenApps/django-tomselect/tree/main/example_project/example).
